### ISSUE TITLE
[help wanted] Cannot find module /lib/index.js

### ISSUE THREAD

**Issue by Aladdin4u** [prashant9428/zipcodeplus#1]
After intalling the npm packages, module is not found. Any way to set it setup locally

**Comment by prashant9428** [comment]
you can setup this locally, can you share some screenshots.

**Comment by Aladdin4u** [comment]
![zipcode](https://user-images.githubusercontent.com/101972392/218738725-ad486321-1ae8-499d-9011-5f138c3297ac.jpg)
that is the error am getting

**Comment by pixelomer** [comment]
You will need to build it first with `npm run build`.

**Comment by Aladdin4u** [comment]
Ok thanks

**Comment by prashant9428** [comment]
This issue has been fixed
